# Generated by Django 2.2.2 on 2020-01-29 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20200129_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
