# Generated by Django 2.2.2 on 2020-01-29 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_usrpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrpost',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
