# Generated by Django 2.2.2 on 2020-01-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20200129_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='userapp/media/'),
        ),
    ]
