# Generated by Django 2.2.2 on 2020-01-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_auto_20200130_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
