# Generated by Django 2.2.2 on 2020-01-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_auto_20200130_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/happycolors.jpg', null=True, upload_to='image/'),
        ),
    ]
