# Generated by Django 2.2.2 on 2020-01-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_auto_20200130_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static_cdn_test/static/happycolors.jpg', null=True, upload_to='image/'),
        ),
    ]
