# Generated by Django 2.2.2 on 2020-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_auto_20200131_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='image/happycolors.jpg', null=True, upload_to='image/'),
        ),
    ]
